import { employees, dependents, documents, settings } from '../data/mock-data.js';
import { calculateEmployeeBenefits, formatCurrency, formatDate } from '../domain/calculations.js';

const statusClass = (status) => status.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s/g, '-');
const badge = (status) => `<span class="badge ${statusClass(status)}">${status}</span>`;
const metric = (label, value, detail, tone = 'neutral') => `<article class="metric-card ${tone}"><span>${label}</span><strong>${value}</strong><small>${detail}</small></article>`;

export function renderDashboard(competency) {
  const active = employees.filter((employee) => employee.status === 'Ativo');
  const admissions = employees.filter((employee) => employee.admission.startsWith(competency));
  const terminations = employees.filter((employee) => employee.termination?.startsWith(competency));
  const calculations = active.map((employee) => calculateEmployeeBenefits(employee, competency, documents));
  const pending = employees.filter((employee) => [employee.amil, employee.dental, employee.totalpass].includes('Pendente')).length + 2;
  const birthdays = active.filter((employee) => employee.birthday.slice(5, 7) === competency.slice(5));
  const vr = calculations.reduce((sum, item) => sum + item.vrNet, 0);
  const vt = calculations.reduce((sum, item) => sum + item.vtNet, 0);
  return `<section class="page-heading"><div><p class="eyebrow">Visao geral / ${competency === '2026-09' ? 'Setembro 2026' : 'Agosto 2026'}</p><h1>Bom dia, Thaina<span>.</span></h1><p class="intro">Aqui esta o que precisa da sua atencao antes do fechamento.</p></div><button class="primary-button" data-action="new-employee"><span>+</span> Novo colaborador</button></section>
    <div class="metric-grid">${metric('Colaboradores ativos', active.length, '+1 desde o ultimo mes', 'green')}${metric('Admissoes no mes', admissions.length, '1 aguardando inclusao', 'blue')}${metric('Desligamentos', terminations.length, 'Processados na competencia', 'neutral')}${metric('Pendencias abertas', pending, '2 criticas para hoje', 'red')}</div>
    <div class="dashboard-grid"><section class="panel attention-panel"><div class="panel-header"><div><p class="eyebrow">Central de atencao</p><h2>O que pede acao</h2></div><button class="text-button" data-view="dependents">Ver todas <span>-></span></button></div><div class="attention-list"><button class="attention-item critical" data-view="employees"><span class="attention-icon">!</span><span><strong>Bianca Almeida sem tipo de transporte</strong><small>Impossivel concluir o calculo de VT</small></span><b>Hoje</b></button><button class="attention-item critical" data-view="benefits"><span class="attention-icon">!</span><span><strong>1 inclusao Amil pendente</strong><small>Bianca Almeida - admissao em 15/09</small></span><b>Hoje</b></button><button class="attention-item warning" data-view="dependents"><span class="attention-icon">~</span><span><strong>Dependente nao enviado a Crowe</strong><small>Lia Almeida - salario-familia e IR</small></span><b>2 dias</b></button><button class="attention-item warning" data-view="documents"><span class="attention-icon">~</span><span><strong>Atestado aguardando envio</strong><small>Rafael Nunes - 11 a 12/09</small></span><b>3 dias</b></button></div></section><section class="panel calculation-panel"><div class="panel-header"><div><p class="eyebrow">Estimativa da competencia</p><h2>Custo projetado</h2></div><button class="icon-button small" title="Atualizar calculo" data-action="refresh">↻</button></div><div class="cost-total">${formatCurrency(vr + vt)}<span>VR + VT liquidos</span></div><div class="cost-row"><span><i class="legend vr"></i>Vale-refeicao</span><strong>${formatCurrency(vr)}</strong></div><div class="cost-row"><span><i class="legend vt"></i>Vale-transporte</span><strong>${formatCurrency(vt)}</strong></div><div class="progress-track"><span style="width:${Math.min((vr / (vr + vt || 1)) * 100, 100)}%"></span></div><small class="calculation-note">Baseada em ${active.length} colaboradores ativos e suas escalas individuais.</small></section></div>
    <div class="dashboard-grid bottom-grid"><section class="panel"><div class="panel-header"><div><p class="eyebrow">Calendario RH</p><h2>Datas importantes</h2></div><button class="text-button" data-view="competencies">Abrir competencia <span>-></span></button></div><div class="calendar-row"><div class="calendar-date"><strong>15</strong><span>SET</span></div><div><strong>Admissao de Bianca Almeida</strong><small>Comercial / CLT</small></div><span class="calendar-tag">Hoje</span></div><div class="calendar-row"><div class="calendar-date"><strong>22</strong><span>SET</span></div><div><strong>Aniversario de Marina Costa</strong><small>Smash Card ainda nao solicitado</small></div><span class="calendar-tag pending-tag">Pendente</span></div></section><section class="panel birthdays"><div class="panel-header"><div><p class="eyebrow">Smash Card / Setembro</p><h2>Aniversariantes</h2></div><span class="count-badge">${birthdays.length}</span></div>${birthdays.map((employee) => `<div class="birthday-row"><div class="avatar">${employee.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div><strong>${employee.name}</strong><small>${formatDate(employee.birthday)}</small></div>${employee.smashCard ? badge('Entregue') : badge('Pendente')}</div>`).join('')}</section></div>`;
}

export function renderEmployees() {
  return `<section class="page-heading"><div><p class="eyebrow">Cadastros / Base funcional</p><h1>Colaboradores<span>.</span></h1><p class="intro">Dados funcionais, jornadas e informacoes para calculo.</p></div><button class="primary-button" data-action="new-employee"><span>+</span> Novo colaborador</button></section><section class="panel table-panel"><div class="toolbar"><label class="search-box">⌕<input id="employee-search" type="search" placeholder="Buscar por nome, cargo ou matricula"></label><div class="toolbar-actions"><select id="department-filter"><option value="">Todos os departamentos</option><option>Operacoes</option><option>Tecnologia</option><option>Comercial</option><option>Financeiro</option><option>Recursos Humanos</option></select><button class="secondary-button" data-action="export">Exportar CSV</button></div></div><div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Departamento</th><th>Jornada / horario</th><th>Admissao</th><th>Transporte</th><th>Status</th><th></th></tr></thead><tbody id="employees-body">${employeeRows(employees)}</tbody></table></div></section>`;
}

function employeeRows(list) { return list.map((employee) => `<tr><td><div class="person-cell"><div class="avatar">${employee.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div><strong>${employee.name}</strong><small>${employee.registration} · ${employee.role}</small></div></div></td><td>${employee.department}</td><td><strong>${employee.schedule}</strong><small>${employee.workHours}</small></td><td>${formatDate(employee.admission)}</td><td>${employee.transport || '<span class="missing">Nao informado</span>'}</td><td>${badge(employee.status)}</td><td><button class="row-action" data-action="edit-employee" data-id="${employee.id}" title="Editar">...</button></td></tr>`).join(''); }

export function renderBenefits(competency) {
  const calculations = employees.filter((employee) => employee.status === 'Ativo').map((employee) => ({ employee, calculation: calculateEmployeeBenefits(employee, competency, documents) }));
  return `<section class="page-heading"><div><p class="eyebrow">Operacao / Calculos e adesoes</p><h1>Beneficios<span>.</span></h1><p class="intro">Acompanhe inclusoes e estime VR e VT por escala individual.</p></div><button class="secondary-button" data-action="export">Exportar CSV</button></section><div class="benefit-tabs"><button class="active">Resumo mensal</button><button>Amil</button><button>Odonto</button><button>TotalPass</button></div><div class="metric-grid benefit-metrics">${metric('VR estimado', formatCurrency(calculations.reduce((sum, item) => sum + item.calculation.vrNet, 0)), 'Valor liquido da competencia', 'green')}${metric('VT estimado', formatCurrency(calculations.reduce((sum, item) => sum + item.calculation.vtNet, 0)), 'Apos desconto de 6%', 'blue')}${metric('Inclusoes pendentes', '4', '1 colaborador recem-admitido', 'red')}${metric('Titulares Amil', '5 / 5', 'Obrigatorio para CLT', 'neutral')}</div><section class="panel table-panel"><div class="panel-header"><div><p class="eyebrow">Competencia ${competency}</p><h2>Calculo por colaborador</h2></div><span class="formula-note">Regras em Configuracoes</span></div><div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Dias elegiveis</th><th>Descontos</th><th>VR liquido</th><th>VT bruto</th><th>VT desconto</th><th>Status</th></tr></thead><tbody>${calculations.map(({ employee, calculation }) => `<tr><td><div class="person-cell"><div class="avatar">${employee.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div><strong>${employee.name}</strong><small>${employee.schedule} · ${employee.transport || 'Transporte pendente'}</small></div></div></td><td><strong>${calculation.eligibleDays}</strong> dias<small>${calculation.directDays} diretos</small></td><td>${calculation.discountDays ? `<span class="discount-text">${calculation.discountDays} dia(s) VR/VT</span>` : 'Nenhum'}</td><td><strong>${formatCurrency(calculation.vrNet)}</strong><small>${calculation.vrDays} creditados</small></td><td>${formatCurrency(calculation.vtGross)}</td><td>${formatCurrency(calculation.vtDiscount)}</td><td>${employee.transport ? badge(employee.amil) : badge('Pendente')}</td></tr>`).join('')}</tbody></table></div></section>`;
}

export function renderPlaceholder(title, eyebrow) { return `<section class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}<span>.</span></h1><p class="intro">Este modulo esta preparado para a proxima etapa do prototipo.</p></div></section><section class="empty-state panel"><div class="empty-icon">+</div><h2>Modulo em construcao</h2><p>A estrutura de dados e as pendencias relacionadas ja estao previstas na arquitetura.</p><button class="secondary-button" data-view="dashboard">Voltar ao dashboard</button></section>`; }

export function bindEmployeeSearch() {
  const search = document.querySelector('#employee-search');
  const filter = document.querySelector('#department-filter');
  const update = () => {
    const query = search.value.toLowerCase();
    const department = filter.value;
    const result = employees.filter((employee) => `${employee.name} ${employee.role} ${employee.registration}`.toLowerCase().includes(query) && (!department || employee.department === department));
    document.querySelector('#employees-body').innerHTML = employeeRows(result);
  };
  search?.addEventListener('input', update);
  filter?.addEventListener('change', update);
}

export function bindViewActions(onNavigate, showToast) {
  document.querySelectorAll('[data-view]').forEach((element) => element.addEventListener('click', () => onNavigate(element.dataset.view)));
  document.querySelectorAll('[data-action="new-employee"]').forEach((element) => element.addEventListener('click', () => showToast('Formulario de colaborador sera liberado na proxima etapa.')));
  document.querySelectorAll('[data-action="export"]').forEach((element) => element.addEventListener('click', () => showToast('Exportacao preparada para o relatorio atual.')));
  document.querySelectorAll('[data-action="refresh"]').forEach((element) => element.addEventListener('click', () => showToast('Calculo atualizado com as regras da competencia.')));
}